hash-format = "sha256"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/argonauts.pw.toml"
metafile = true

[[files]]
file = "mods/cadmus.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/heracles.pw.toml"
metafile = true

[[files]]
file = "mods/hexal-fabric-1.20.1-0.3.0-2.jar"

[[files]]
file = "mods/hexcasting.pw.toml"
metafile = true

[[files]]
file = "mods/hexxy-dimensions-1.3.0.jar"

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreiotas-fabric-1.20.1-0.1.0-4.jar"

[[files]]
file = "mods/mouse-wheelie.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/plethora-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/prometheus.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/texts/splashes.txt"

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/textures/gui/title/background/panorama_0.png"

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/textures/gui/title/background/panorama_1.png"

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/textures/gui/title/background/panorama_2.png"

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/textures/gui/title/background/panorama_3.png"

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/textures/gui/title/background/panorama_4.png"

[[files]]
file = "resourcepacks/hajpack/assets/minecraft/textures/gui/title/background/panorama_5.png"

[[files]]
file = "resourcepacks/hajpack/pack.mcmeta"

[[files]]
file = "resourcepacks/hajpack/pack.png"
