hash-format = "sha256"

[[files]]
file = "config/yosbr/options.txt"
hash = "b3561d15b4cb62add9bf7211dd2b13c73762f156546602081b8185c0027f41aa"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "0cbcd58c49decc0ecbccd330fcc8326e3b8769e22e1740e229f09541acf3df7f"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "0c2ef257e81e629a1016ef48089d71c442152ac2a565150456cb979afb663c44"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a89dfcc985612a275975d4823a24fc3dceb244bacb2e8f81bd459283bf1b9fe9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "e3272db811c06088fee691b5338e922681073fbc4f0e55a7d3865abb8b62eb0e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "a856296531bab559c7dbe061827078e206b9cf194be3be618c462c62ab4fd841"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "23bd1bd72faedf4bb2d6acf2db2441544d2744cfb76f56b8c8165abc25cfeb59"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "cd49906a91e2ff1c11acba79192d609c232f2f73d82cc6a646e7338c8e76aa8a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f2855ca462a5ef36206a941612989aed049b1cd49559f0f2d4d247505566e546"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "ec7f94fcb88b139515557631074b5e90e64ea53761eb5753c2492007e24f59c4"
metafile = true
