name = "hajpack"
author = "the hajpack team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
