name = "hajpack"
author = "the hajpack team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59857b1ce1e32ebbf1678a0b21b0bea04fb1113a595450134132de5a3bd67860"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
