name = "hajpack"
author = "the hajpack team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7234af7f235e6db5ec5c49435bcfc51a3516db460276f7a46e4f7f9adca72d9b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
